### ISSUE TITLE
ACEnet issues

### ISSUE THREAD

**Issue by chunxia0202** [ymli39/ACEnet-for-Neuroanatomy-Segmentation#1]
Hello,I have a few questions in restore to the Acenet experiment.
Coase-grained segmentation's performance is the same as in the paper,dice_score can reach 0.89.The chart below shows the predicted results:
![image](https://user-images.githubusercontent.com/65805278/121809734-98739280-cc90-11eb-9f2b-02f35cd3e875.png)
However fine-grained segmentation's performance is very poor,dice_score can only reach 0.2.The chart below shows the predicted results:
![image](https://user-images.githubusercontent.com/65805278/121809751-a45f5480-cc90-11eb-865b-8aac1c6faa0c.png)
I also use test_demo.py to check the data preformance,The results are good at coarse-grained.Blow are pred.nii.gz and skull.nii.gz
![image](https://user-images.githubusercontent.com/65805278/121809874-28194100-cc91-11eb-891e-7dd2911b0ddc.png)
![image](https://user-images.githubusercontent.com/65805278/121809877-2a7b9b00-cc91-11eb-88f1-4870e6a8dcda.png)
However the results are very poor at fine-grained.
![image](https://user-images.githubusercontent.com/65805278/121809903-467f3c80-cc91-11eb-8206-bfbeb670f182.png)
![image](https://user-images.githubusercontent.com/65805278/121809905-48e19680-cc91-11eb-8542-98f037bca36f.png)
So I wonder if there is something wrong with fine-grained labels generation.MICCAI2012 datasets have 133 fine structures,however But 139 labels are generated here.

**Comment by ymli39** [comment]
I tested my code, my results looks good. 
Please see the attached image below:
![Capture](https://user-images.githubusercontent.com/16530874/121822658-44f04d00-cc6e-11eb-9808-c7e1a90af756.PNG)

I think either something with your input or visualization.

**Comment by chunxia0202** [comment]
Is this the result of fine-grained segmentation or coarse-grained segmentation?
My coarse-grained segmentation results are good.  Here are my results:
![image](https://user-images.githubusercontent.com/65805278/121831819-0f457580-ccfb-11eb-88ad-6f6ad7425ee6.png)
However it is very poor at fine-grained segmentation.If there is something wrong with input,Why does it perform well in coarse-grained segmentation.
As for visualization,I used test_demo/test.py to generate the results directly and then displayed them on ITK-SNAP.
By the way, how does this colored label appear,my result graph is grey.
Thank you for your answer.
Wish you peace and health on Dragon Boat Festival.

**Comment by ymli39** [comment]
My updated images are for fine-grained segmentation. I didn't see much variations on your coarse-grained results either.
For displaying colors you need to change the colormap from your visualization tool.

**Comment by chunxia0202** [comment]
Thanks for your answer.My fine-grained results are poor,I don't know what went wrong,no matter I use segmentation/train.py or test_demo/test.py. There should be no problem with my pre-processing process.
Here are my fine-grained segmentation results:
![image](https://user-images.githubusercontent.com/65805278/121850328-3150ef00-cd1f-11eb-8cf6-ea239d395517.png)
And Below are my coarse-grained segmentation results:
![image](https://user-images.githubusercontent.com/65805278/121850557-8987f100-cd1f-11eb-921c-0edc047ac749.png)
