### ISSUE TITLE
ACEnet results 

### ISSUE THREAD

**Issue by chunxia0202** [ymli39/ACEnet-for-Neuroanatomy-Segmentation#3]
Hello author.Recently, I have done some preprocessing again, and I found that the images and labels slicing methodswere different before, so the performance was not good. I recently adjusted the preprocessing, and found that theeffect was good, this is the result of it.The fine-grained segmentation performance can be achieved 0.776,and coarse-grained segmentation performance can be achieved 0.900

This is the result of fine- grained segmentation:
![image](https://user-images.githubusercontent.com/65805278/122501176-c822f180-d026-11eb-966a-bc41f20f4431.png)
![image](https://user-images.githubusercontent.com/65805278/122501189-cc4f0f00-d026-11eb-8767-35b1c58fa293.png)

This is the result of coarse-grained segmentation:
![image](https://user-images.githubusercontent.com/65805278/122501201-d07b2c80-d026-11eb-8189-c787d59d2b3c.png)

But my visualization results for the left and right brain segmentation color is the same, such a result is correct?

**Comment by ymli39** [comment]
You could check the visualization with other colormaps, maybe 'HSV'. If you have no further questions, you could close your currently opened issues.
