### ISSUE TITLE
Dataset unavaliable.

### ISSUE THREAD

**Issue by GYDDHPY** [ymli39/ACEnet-for-Neuroanatomy-Segmentation#6]
Hi, can you share the 2012 Multi-Atlas Labeling Challenge dataset? I tried to apply for the dataset through official website but no response is returned.

**Comment by ymli39** [comment]
Hi, unfortunately, I cannot share the dataset due to the license issue.

**Comment by GYDDHPY** [comment]
> Hi, unfortunately, I cannot share the dataset due to the license issue.

I see. How did you apply for the dataset? Did you use the contact form provided by the website and write the request in it? Does the website keep you waiting for long time?

**Comment by ymli39** [comment]
They used to have a different website to apply for the dataset. I have also double-checked with their company, the site is still working and they specifically told me to not share the dataset with anybody else. They said they will handle all the dataset requests soon.

**Comment by GYDDHPY** [comment]
Thank you for your concern!  
The website finally gave me a download link. However, the label file seems to be the fine-grained version. I didn't find the coarse-grained label you mentioned in your paper. How did you get the coarse-grained label? Do I need to transform the fine-grained label to get the coarse-grained version?

**Comment by ymli39** [comment]
the preprocessing function is here: https://github.com/ymli39/ACEnet-for-Neuroanatomy-Segmentation/blob/3439ff9064ce2042fcfaf8e15856c79c5897a378/data_utils/utils.py#L32

**Comment by GYDDHPY** [comment]
Thank you for your quick reply.
